# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pioluk/azure-pipelines-test'

steps:
# - script: docker login -u $(dockerId) -p $(dockerPassword)
#   displayName: 'docker login'
# - script: docker build -f Dockerfile -t $(imageName):$(Build.BuildId) -t $(imageName):$(Build.SourceVersion) -t $(imageName):latest .
#   displayName: 'docker build'
# - script: docker push $(imageName)
#   displayName: 'docker push'
- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: $(imageName):$(Build.BuildId)
- task: Docker@1
  displayName: 'Push an image'
  inputs:
    command: 'Push an image'
    imageName: $(imageName):$(Build.BuildId)
    includeSourceTags: true
